spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: service-system
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mini_server_db?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      #初始连接个数
      initial-size: 10
      #最小连接池数量
      min-idle: 10
      #最大连接池数量
      maxActive: 200
      #最大等待时间ms
      maxWait: 60000
      #destory线程检测连接的间隔时间，连接空闲时间大于minEvictableIdleTimeMillis时，则关闭物理连接
      timeBetweenEvictionRunsMillis: 60000
      #连接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMillis: 300000
      #用来检测连接是否有效的sql
      validationQuery: select 'x'
      #申请连接时检测，保证安全性
      testWhileIdle: true
      #连接异常重试次数
      connectionErrorRetryAttempts: 3
      breakAfterAcquireFailure: true
      timeBetweenConnectErrorMillis: 300000
      asyncInit: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      transaction-query-timeout: 6000
      filters: stat,wall,log4j2
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow:
        deny:
        reset-enable: false
        login-username: admin
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  #nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#logging:
#  level:
#    root: debug
mybatis-plus:
  # 读取mybatis配置文件
  #  config-location: classpath:mybatis/mybatis-config.xml
  # 读取mapper文件
  #  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  # 别名配置，在mybatis.xml文件resultType属性可以不指定类的全路径
  #  type-aliases-package: com.hikktn.pojo
  # 开启驼峰映射，注意：配置configuration.map-underscore-to-camel-case则不能配置config-location
  #  configuration:
  #    map-underscore-to-camel-case: true
  # 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8009

knife4j:
  #开启增强配置
  enable: true

admin:
  id: 1
